version: '3.9'
services:
  fetcher:
    container_name: fetcher
    restart: always
    network_mode: "host"
    build:
      context: ./fetcher
  gateway:
    container_name: gateway
    restart: always
    network_mode: "host"
    build:
      context: ./gateway

