version: '3.9'
services:
  fetcher:
    container_name: fetcher
    build:
      context: ./fetcher
  gateway:
    container_name: gateway
    build:
      context: ./gateway
    ports:
      - "8089:8089"
  webapp:
    container_name: webapp
    build:
      context: ./webapp
    ports:
      - "3000:80"

