server:
  port: 8089

spring:
  cloud:
    gateway:
      routes:
        - id: fetcher_route
          uri: http://fetcher:8070
          predicates:
          - Path=/rss/**
          - Header=Authorization
          filters:
          - StripPrefix=1
          - ApiAuth
        - id: portal_route
          uri: http://portal:3000
          predicates:
          - Path=/portal/**
          - Header=Authorization
          filters:
          - StripPrefix=1
          - ApiAuth
        - id: login_route
          uri: http://portal:3000
          predicates:
          - Path=/login/**
          filters:
          - StripPrefix=1

