server:
  port: 8089

spring:
  cloud:
    gateway:
      routes:
        - id: fetcher_route_api
          uri: http://fetcher:8070
          predicates:
          - Path=/api/**
          - Header=Authorization
          filters:
          - StripPrefix=1
          - ApiAuth
          - Quota
        - id: fetcher_route_web
          uri: http://fetcher:8070
          predicates:
          - Path=/api/**
          - Cookie=ownportal, .*
          filters:
          - StripPrefix=1
          - WebAuth
          - Quota
        - id: portal_route
          uri: http://portal:8077
          predicates:
          - Path=/portal/**
          filters:
          - StripPrefix=1
          - WebAuth
        - id: user
          uri: http://portal:8077
          predicates:
          - Path=/user/**
        - id: developer
          uri: http://portal:8077
          predicates:
          - Path=/developer/**
