# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 200
  journal_mode: wal
  encoding: utf8

development:
  <<: *default
  database: db/ownportal_development.sqlite3

test:
  <<: *default
  database: db/ownportal_test.sqlite3

production:
  <<: *default
  database: db/ownportal_production.sqlite3

