Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/SymbolArray:
  Enabled: false
